name: Deploy Workflow
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      VITE_API_URL: ${{ vars.VITE_API_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: npm i && npm run build
      - name: Copy bundle via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist,nginx"
          target: "./static"
      - name: Setup server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker stop nginx || true && sudo docker run --name nginx -v /home/ubuntu/static/nginx/config:/etc/nginx/conf.d -v /home/ubuntu/static/dist:/dist:ro -p 80:80 --rm -d nginx
